echo "; Batch file to backup Knight Orc part 2"
md b:\games.l9
md b:\games.l9\knight2.l9
md b:\games.l9\knight2.l9\st.l9

copy \games.l9\knight2.l9\*.* b:\games.l9\knight2.l9\
copy \games.l9\knight2.l9\st.l9\squash.dat b:\games.l9\knight2.l9\st.l9\
copy \games.l9\knight2.l9\st.l9\mmessage.txt b:\games.l9\knight2.l9\st.l9\
copy \games.l9\knight2.l9\st.l9\hmessage.txt b:\games.l9\knight2.l9\st.l9\
copy \games.l9\knight2.l9\st.l9\30 b:\games.l9\knight2.l9\st.l9\30
