echo "; Batch file to make a dummy Knight Orc part 1 for running part 2"
md b:\games.l9
md b:\games.l9\knight1.l9
md b:\games.l9\knight1.l9\st.l9

copy \games.l9\knight1.l9\aconst.txt b:\games.l9\knight1.l9\
copy \games.l9\knight1.l9\mconst.txt b:\games.l9\knight1.l9\
copy \games.l9\knight1.l9\acore.txt b:\games.l9\knight1.l9\
copy \games.l9\knight1.l9\aparse.txt b:\games.l9\knight1.l9\
copy \games.l9\knight1.l9\npc.txt b:\games.l9\knight1.l9\
copy \games.l9\knight1.l9\oops.txt b:\games.l9\knight1.l9\
copy \games.l9\knight1.l9\converse.txt b:\games.l9\knight1.l9\


