1
**look at picture*
**examine hourglass*
**north**
**take matches and candle. examine clock and wind it**
**in**
****drop everything*
**examine cogs*
*examine pendulum*
**turn cog 1. push pendulum*
*north*
**west*
**west*
**open door. west*
**take spear and examine it*
**south*
*open cupboard* 
*west*
**open door. west*
**southwest*
**get keys*
**e*
*e*
**examine compost heap*
*east*
**examine car.down*
**turn cog 2. push pendulum*
**brief*
**get matches.n.n.n.n.e**
**empty petrol*
*light match*
**e*
**up. up*
*take bone. up*
**offer bone to tiger*
**examine tin of catfood*
*give kattomush to the tiger*
**yes*
***verbose.turn 4.push pend.n*
************undo**
turn 5.push pend.n*
************undo**
turn 6.push pend*
light a match.n*
************undo**
turn 8.push pend.n*
************restart*
*y